export const GET_IP_RESTRICTIONS = 'GET_IP_RESTRICTIONS';
export const SET_IP_RESTRICTIONS_LOADING = 'SET_IP_RESTRICTIONS_LOADING';
export const CREATE_IP_RESTRICTION = 'CREATE_IP_RESTRICTION';
export const CLEAR_IP_RESTRICTION_SEARCH_QUERY = 'CLEAR_IP_RESTRICTION_SEARCH_QUERY';
export const SHOW_IP_RESTRICTION_FORM = 'SHOW_IP_RESTRICTION_FORM';
export const CLOSE_IP_RESTRICTION_FORM = 'CLOSE_IP_RESTRICTION_FORM';