export const GET_DEPARTMENTS = 'GET_DEPARTMENTS';
export const SET_DEPARTMENTS_LOADING = 'SET_DEPARTMENTS_LOADING';
export const SET_DEPARTMENTS_SEARCH_QUERY = 'SET_DEPARTMENTS_SEARCH_QUERY';
export const CLEAR_DEPARTMENTS_SEARCH_QUERY = 'CLEAR_DEPARTMENTS_SEARCH_QUERY';
export const SHOW_DEPARTMENT_FILTER = 'SHOW_DEPARTMENT_FILTER';
export const CLOSE_DEPARTMENT_FILTER = 'CLOSE_DEPARTMENT_FILTER';
export const SHOW_DEPARTMENT_VIEW = 'SHOW_DEPARTMENT_VIEW';
export const CLOSE_DEPARTMENT_VIEW = 'CLOSE_DEPARTMENT_VIEW';
export const SHOW_DEPARTMENT_FORM = 'SHOW_DEPARTMENT_FORM';
export const CLOSE_DEPARTMENT_FORM = 'CLOSE_DEPARTMENT_FORM';
export const SET_DEPARTMENT_FORM_LOADING = 'SET_DEPARTMENT_FORM_LOADING';

export const DEPARTMENT_TYPES = {
    1: 'Default',
    2: 'Group'
}