export const GET_DEPARTMENTS = 'GET_DEPARTMENTS';
export const SET_DEPARTMENTS_LOADING = 'SET_DEPARTMENTS_LOADING';
export const SET_DEPARTMENTS_SEARCH_QUERY = 'SET_DEPARTMENTS_SEARCH_QUERY';
export const CLEAR_DEPARTMENTS_SEARCH_QUERY = 'CLEAR_DEPARTMENTS_SEARCH_QUERY';