export const EXPORT_ALL = 1;
export const EXPORT_FILTER = 2;
export const EXPORT_IDS = 3;
export const SHOW_EXPORT_MODAL = 'SHOW_EXPORT_MODAL';
export const CLOSE_EXPORT_MODAL = 'CLOSE_EXPORT_MODAL';
export const EXPORT_LOADING_TRUE = 'EXPORT_LOADING_TRUE';
export const EXPORT_LOADING_FALSE = 'EXPORT_LOADING_FALSE';
